name: Build Python Executable (Windows)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write  # Needed for GitHub release upload

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Detect data files for PyInstaller
      shell: pwsh
      run: |
        $files = Get-ChildItem -Recurse -File | Where-Object {
          $_.Extension -notin @(".py", ".pyc", ".pyo", ".spec")
        }
        $addDataArgs = @()
        foreach ($file in $files) {
          $relPath = $file.FullName.Substring((Get-Location).Path.Length + 1)
          $destDir = Split-Path $relPath
          if (-not [string]::IsNullOrWhiteSpace($destDir)) {
            $addDataArgs += "--add-data `"${relPath};${destDir}`""
          } else {
            $addDataArgs += "--add-data `"${relPath};.`""
          }
        }
        $argsLine = $addDataArgs -join " "
        $command = "pyinstaller --onefile --console --hidden-import=PIL $argsLine csbp_v1.py" | Out-File build_command.txt -Encoding ascii

    - name: Build executable with auto data files
      run: |
        $command = Get-Content build_command.txt -Raw
        Invoke-Expression $command
        echo "Executable built at dist/csbp_v1.exe"

    - name: Test run executable in Actions
      run: |
        echo "Running the executable to check for errors..."
        .\dist\csbp_v1.exe || exit 1

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        files: dist/csbp_v1.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



